Iter18: Документация в формате godoc
real-splendid/url-shortener-practicum pull request #18
Opened 2024-11-09 13:34 UTC by real-splendid

2024-11-12 04:06 UTC, vokinneberg requested changes
Поздравляю с первым ревью седьмого спринта! 🎉  Ты сделал улучшения своего приложения, и оно проходит автотесты 👍 Тем не менее, хочу сделать несколько предложений и комментариев относительно твоего кода. 🤓

**Сильные стороны твоего PR:**

1. Твой код отформатирован с использованием `gofmt` и `goimport`.
2. Ты реализовал примеры и бенчмарки. 💪
3. Ты добавил документацию godoc.
4. Ты снял профиль приложения и сделал улучшения производительности.

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Было бы здорово добавить автоматическое вычисление покрытия в CI pipeline при помощи github actions. Можно так же добавить badge, который будет показывать процент покрытия тестами проекта, в README файл. Как это сделать можно посмотреть вот здесь, например https://github.com/vladopajic/go-test-coverage
2. Покрытие тестами сейчас всего лишь 23.4%, в то время, как по условию задачи требуется не менее 40%.

2024-11-12 04:06 UTC, vokinneberg commented on internal/handlers/shorten.go
> +	const maxBodySize = 1024 * 1024
Я бы советовал вынести константу в начало файла на уровень пакета.

2024-11-17 09:37 UTC, real-splendid commented on internal/handlers/shorten.go
> +	const maxBodySize = 1024 * 1024
вынес константу на уровень пакета

2024-11-17 09:40 UTC, real-splendid commented
> 1. Было бы здорово добавить автоматическое вычисление покрытия в CI pipeline при помощи github actions.

Сделал github action для покрытия с проверкой с проверкой, что оно не меньше 40%. Добавил бейдж в readme.

> 2. Покрытие тестами сейчас всего лишь 23.4%, в то время, как по условию задачи требуется не менее 40%.

Довёл покрытие до 40%

2024-11-22 02:14 UTC, vokinneberg approved these changes
Поздравляю с успешным ревью седьмого спринта! 🎉 

2024-11-22 12:52 UTC, merged